load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "vpm",
    srcs = [
        "main.cpp",
        "BuildGenerator.cpp",
        "BuildGenerator.hpp",
    ],
    deps = [],
    copts = ["-std=c++17"],
    visibility = ["//visibility:public"],
) 